# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("generate_report_summary works", {
  expect_true(inherits(generate_report_summary, "function")) 
})
