# WARNING - Generated by {fusen} from dev/flat_plots_region.Rmd: do not edit by hand # nolint: line_length_linter.

# test_that("plot_reg_solution works", {   expect_true(inherits(plot_reg_solution, "function")) })
