# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ai_factory and apply_sdc work", {
  expect_true(inherits(unhcr_ai_engine, "function"))
  expect_true(inherits(apply_sdc, "function"))
  
  df <- data.frame(count = c(0, 3, 10))
  df_sdc <- apply_sdc(df, min_threshold = 5)
  expect_true(is.na(df_sdc$count[2]))
  expect_equal(df_sdc$count[1], 0)
  expect_equal(df_sdc$count[3], 10)
})
