# WARNING - Generated by {fusen} from dev/flat_plots_country.Rmd: do not edit by hand # nolint: line_length_linter.

# test_that("plot_ctr_origin_history works", {   expect_true(inherits(plot_ctr_origin_history, "function")) })
