# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("generate_plot_story handles missing keys gracefully", {
    # Mock Sys.getenv to return empty
    withr::with_envvar(c("OPENAI_API_KEY" = ""), {
        p <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) +
            ggplot2::geom_point()
        res <- generate_plot_story(p)
        expect_match(res, "skipped")
    })
})
