# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_llm_response works", {
  expect_true(inherits(clean_llm_response, "function"))
})
