# WARNING - Generated by {fusen} from dev/flat_reports.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("generate_report works", {
  expect_true(inherits(generate_report, "function"))
})
