# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' UNHCR AI Engine Factory
#'
#' centralized AI Factory pattern using `ellmer`
#'
#' @param provider one of "gemini", "openai", "claude" (Default: "gemini")
#' @param task_type one of "summarization" (fast) or "reasoning" (high quality)
#' @param use_caching boolean (default TRUE)
#'
#' @return an ellmer chat object
#' @importFrom ellmer chat_google_gemini chat_anthropic chat_openai
#' @export
unhcr_ai_engine <- function(provider = c("gemini", "openai", "claude"), 
                            task_type = c("summarization", "reasoning"),
                            use_caching = TRUE) {
  
  provider <- match.arg(provider)
  task <- match.arg(task_type)
  
  if (provider == "gemini") {
    # Gemini 3.0 Pro for complex reasoning, Flash for volume
    model_id <- ifelse(task == "reasoning", "gemini-2.0-pro-exp-02-05", "gemini-1.5-flash")
    # model_id <- ifelse(task == "reasoning", "gemini-2.0-flash-thinking-exp-01-21", "gemini-1.5-flash")
    
    # Implicit caching works automatically for large contexts (Pro > 4096 tokens)
    return(ellmer::chat_google_gemini(
      model = model_id,
      safety_settings = list(
        list(category = "HARM_CATEGORY_HARASSMENT", threshold = "BLOCK_ONLY_HIGH"),
        list(category = "HARM_CATEGORY_HATE_SPEECH", threshold = "BLOCK_ONLY_HIGH")
      )
    ))
  } 
  
  if (provider == "openai") {
    return(ellmer::chat_openai(model = "gpt-4o-mini"))
  }
  
  if (provider == "claude") {
    return(ellmer::chat_anthropic(model = "claude-3-5-sonnet-latest", cache = "ephemeral"))
  }
}
