# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' Call AI Engine with Caching
#'
#' A memoised wrapper around the AI interaction to prevent redundant calls.
#'
#' @param chat An initialized ellmer chat object.
#' @param prompt The user prompt.
#' @param system_prompt Optional system prompt.
#' @param cache_dir The directory to store the cache.
#'
#' @return The AI response string.
#' @importFrom memoise memoise cache_filesystem
#' @importFrom cachem cache_disk
#' @importFrom digest digest
#' @export
call_ai_engine_memoised <- function(chat, prompt, system_prompt = NULL, cache_dir = unhcr_cache_dir()) {
  
  # Helper to perform the actual chat
  # We define it locally but we need to ensure it's not re-memoised every time 
  # with a different environment if passed to memoise. 
  # Since we are manually creating the cache object and checking keys, 
  # we don't strictly need memoise::memoise() on the function object itself 
  # if we handle the logic. 
  # But the requirement says: "Wrap the internal _call_llm logic using memoise::memoise()."
  
  # If we just want to follow the pattern of checking cache first:
  
  cd <- cachem::cache_disk(cache_dir)
  
  # Create a unique key based on inputs
  # We treat 'chat' class/config as part of key if possible, or assume caller responsibility.
  # Using `capture.output(print(chat))` is a decent proxy for chat config (model, provider).
  key <- digest::digest(list(
    prompt = prompt, 
    system_prompt = system_prompt, 
    chat_config = utils::capture.output(print(chat))
  ))
  
  cached_res <- cd$get(key)
  if (!is.null(cached_res) && !inherits(cached_res, "key_missing")) {
    return(cached_res)
  }
  
  # Execute
  full_prompt <- if (!is.null(system_prompt)) paste(system_prompt, prompt, sep = "\n\n") else prompt
  
  res <- tryCatch({
    chat$chat(full_prompt)
  }, error = function(e) {
    stop(e)
  })
  
  # Set cache
  cd$set(key, res)
  
  res
}

#' Get UNHCR Cache Directory
#'
#' Returns a persistent cache directory for the package.
#'
#' @return A string containing the path to the cache directory.
#' @importFrom tools R_user_dir
#' @export
unhcr_cache_dir <- function() {
  cache_dir <- tools::R_user_dir("unhcrreports", which = "cache")
  if (!dir.exists(cache_dir)) {
    dir.create(cache_dir, recursive = TRUE)
  }
  cache_dir
}
