# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply Statistical Disclosure Control
#'
#' Redact small counts to prevent identification.
#'
#' @param data A dataframe or similar object.
#' @param min_threshold Minimum count threshold (default 5).
#'
#' @return Dataframe with redacted values.
#' @export
apply_sdc <- function(data, min_threshold = 5) {
  if (is.null(data)) return(NULL)
  
  # Helper to redact a single vector
  redact_vector <- function(x) {
    if (is.numeric(x)) {
      # Identify values between 0 and threshold (exclusive of 0, inclusive of threshold - 1?)
      # Rule of 5 typically means < 5 are redacted. 0 is usually fine.
      to_redact <- x > 0 & x < min_threshold
      x[to_redact] <- NA # Or 0, depending on specific policy. Using NA for now to indicate redaction.
    }
    x
  }
  
  if (is.data.frame(data) || inherits(data, "data.frame")) {
    data[] <- lapply(data, redact_vector)
  }
  
  data
}
