# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' Extract Plot Structure and Metadata (Phase 1)
#'
#' This function implements Phase 1 of the AI reporting architecture.
#' It extracts visual metadata from a ggplot object by forcing a render build.
#' Unlike simple label extraction, this captures the "trained" ranges and
#' legend mappings that are actually displayed to the user.
#'
#' @param p A `ggplot` object.
#' @return A list containing:
#'   \item{labels}{Title, subtitle, caption, and axis labels.}
#'   \item{ranges}{Exact x and y ranges for each panel (trained).}
#'   \item{guides}{Mapping of visuals (color/shape) to data values.}
#'   \item{geoms}{List of geometric layers used.}
#' @importFrom ggplot2 ggplot_build get_guide_data
#' @importFrom purrr map map_chr
#' @export
extract_structure <- function(p) {
  if (is.null(p)) return(NULL)
  
  # Force layout build to get trained ranges
  built <- ggplot2::ggplot_build(p)
  
  # Extract trained axis ranges (handling facets)
  layout_ranges <- built$layout$panel_params |>
    purrr::map(function(panel) {
      list(
        x_range = panel$x.range,
        y_range = panel$y.range
      )
    })
  
  # Decode legends using get_guide_data (available in ggplot2 >= 3.5.0)
  guides_map <- tryCatch({
    ggplot2::get_guide_data(p)
  }, error = function(e) {
    NULL
  })
  
  # Basic geoms
  geoms <- purrr::map_chr(p$layers, ~ class(.x$geom)[1])
  
  list(
    labels = p$labels,
    ranges = layout_ranges,
    guides = guides_map,
    geoms = geoms,
    scales = p$scales$scales
  )
}
