# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate Plot Description with AI (Phase 3)
#'
#' This function implements Phase 3 of the AI reporting architecture.
#' It serves as the "Semantic Generator," combining structure and statistics
#' to prompt an LLM for a structured description.
#'
#' @param structure Metadata list returned by `extract_structure`.
#' @param stats Statistical profile returned by `profile_data`.
#' @param provider The LLM provider (e.g., "openai", "azure", "anthropic").
#' @param model The specific model to use.
#' @param max_tokens Maximum token limit for the response.
#' @return A list containing:
#'   \item{short_desc}{A concise, WCAG-compliant alt text string.}
#'   \item{long_desc}{A detailed analytical description of the visualization.}
#' @importFrom ellmer chat_openai chat_google_gemini chat_anthropic
#' @importFrom ellmer chat_ollama chat_azure_openai
#' @importFrom utils capture.output
#' @importFrom jsonlite fromJSON
#' @export
generate_description <- function(
  structure,
  stats,
  provider = NULL,
  model = NULL,
  max_tokens = 500
) {
  # Construct Context
  context_str <- paste0(
    "PLOT METADATA:\n",
    "Title: ",
    structure$labels$title,
    "\n",
    "Subtitle: ",
    structure$labels$subtitle,
    "\n",
    "Geoms: ",
    paste(unique(structure$geoms), collapse = ", "),
    "\n",
    "X Label: ",
    structure$labels$x,
    "\n",
    "Y Label: ",
    structure$labels$y,
    "\n\n",
    "STATISTICAL PROFILE:\n",
    "STATISTICAL PROFILE:\n",
    paste(capture.output(print(stats$distributions)), collapse = "\n"),
    "\n",
    "Correlations: ",
    paste(
      names(stats$correlations),
      unlist(stats$correlations),
      sep = ": ",
      collapse = ", "
    ),
    "\n"
  )

  system_prompt <- paste0(
    "You are the Senior Data Storyteller for UNHCR. ",
    "Your task is to translate statistical graphs into humanitarian narratives that inspire action.\n\n",
    "**CRITICAL RULE: ZERO ABSTRACTION**\n",
    "You are strictly FORBIDDEN from using generic placeholders. You must extract the specific names from the STATISTICAL PROFILE.\n",
    "- **BANNED PHRASES:** 'The primary population', 'The largest group', 'A specific nationality', 'The country of origin'.\n",
    "- **REQUIRED FORMAT:** 'Venezuelan refugees', 'Asylum-seekers from Haiti', 'The population in Roraima'.\n",
    "- **Logic:** If the data says 'VEN' or 'Venezuela', you MUST write 'Venezuela'. If the data says 'Refugees', write 'Refugees'. Do not generalize.\n\n",
    "**1. CORE PHILOSOPHY: THE GRAPH IS EVIDENCE, NOT THE STORY.**\n",
    "- **Do NOT describe the chart visuals.** Never say 'The bar chart shows' or 'The blue line'.\n",
    "- **Instead, describe the reality.** If the line goes up, write 'Displacement accelerated'.\n\n",
    "**2. DATA SPECIFICITY (NO ABSTRACTIONS)**\n",
    "- **Naming Rule:** Never use placeholders like 'the largest population group', 'the primary country', or 'a specific nationality'.\n",
    "- **Correction:** You MUST explicitly name the group found in the data (e.g., instead of 'the largest group surged', write 'Venezuelan refugees surged').\n",
    "- **Precision:** If the data distinguishes between 'Refugees' and 'Asylum-Seekers', use the specific term. Do not generalize to 'people'.\n\n",
    "**3. INSTITUTIONAL VOICE (UNHCR STYLE)**\n",
    "- **Tone:** Authoritative, Neutral (on conflict), Protection-Centric, and Action-Oriented.\n",
    "- **Semantics:** 'Illegal' -> 'Irregular'. 'Swarm' -> 'Large-scale movement'. 'Burden' -> 'Responsibility'.\n",
    "- **Privacy:** Suppress any counts < 5 (write 'a small number').\n\n",
    "**4. ANALYTICAL HEURISTICS (INTERPRETING THE VISUALS)**\n",
    "- **Stable:** Change < 5% -> Describe as 'Remained relatively stable'.\n",
    "- **Significant:** Change > 10% -> Describe as 'Marked rise' or 'Significant increase'.\n",
    "- **Surge:** Change > 20% or sudden spike -> Describe as 'Surge' or 'Rapid escalation'.\n",
    "- **Concentration:** If top 3 groups > 50% -> State: 'Displacement is highly concentrated among [Name of Group 1] and [Name of Group 2]'.\n",
    "- **The Gap:** If there is a difference between Needs and Funding, frame it as a 'Protection Gap'.\n\n",
    "**5. NARRATIVE STRUCTURE (JSON OUTPUT)**\n",
    "Generate a strict JSON object with two keys:\n",
    "  * 'short_desc': WCAG-compliant alt text ('* [Chart Type] of [Variables] showing [Trend]*').\n",
    "  * 'long_desc': A 3-5 sentence narrative following this Story Arc:\n",
    "     (A) **The Headline (The Human Impact):** Start with the 'So What'. (e.g., 'Escalating instability has driven record displacement...').\n",
    "     (B) **The Evidence (Specific Names & Numbers):** Support the headline with specifics. **You must name the actors.** \n",
    "        *BAD:* 'The main group increased by 50%.'\n",
    "        *GOOD:* 'The number of **Venezuelan asylum-seekers** rose by 50% to [Number], straining reception capacity.'\n",
    "     (C) **The Context (The Driver):** Briefly mention the root cause if implied (conflict, policy).\n",
    "     (D) **The Call (The Implication):** Conclude with the need for support or the consequence of inaction."
  )


  prompt <- paste0(
    "Context:\n", context_str, "\n\n",
    "Task: Write a narrative for this graph that is specific and actionable.\n",
    "1. **SEARCH:** Look at the 'STATISTICAL PROFILE' above. Find the text labels with the highest numbers (e.g., 'Venezuela', 'Refugees', 'Syria').\n",
    "2. **NAME:** In your response, explicitly name these groups. Do not refer to them as 'the group' or 'the population'.\n",
    "3. **STORY:** Explain *why* this specific group is increasing/decreasing and what it means for the response."
  )

  # Logic to select provider
  # (duplicated from generate_plot_story for now to adhere to modularity)
  if (is.null(provider)) {
    if (!is.na(Sys.getenv("AZURE_OPENAI_ENDPOINT", unset = NA_character_))) {
      provider <- "azure"
    } else if (!is.na(Sys.getenv("OPENAI_API_KEY", unset = NA_character_))) {
      provider <- "openai"
    } else if (!is.na(Sys.getenv("GEMINI_API_KEY", unset = NA_character_))) {
      provider <- "gemini"
    } else if (!is.na(Sys.getenv("ANTHROPIC_API_KEY", unset = NA_character_))) {
      provider <- "anthropic"
    } else {
      stop("No supported API key found.")
    }
  }

  provider <- tolower(provider)
  if (is.null(model)) {
    model <- switch(provider,
      openai = "gpt-4o-mini",
      gemini = "gemini-2.0-flash",
      anthropic = "claude-3-5-sonnet-latest",
      ollama = "deepseek-r1",
      azure = "gpt-4",
      stop("Invalid provider")
    )
  }

  chat <- switch(provider,
    openai = ellmer::chat_openai(
      model = model,
      system_prompt = system_prompt,
      type = "json_object"
    ),
    azure = {
      azure_key <- Sys.getenv("AZURE_OPENAI_API_KEY")
      azure_endpoint <- Sys.getenv("AZURE_OPENAI_ENDPOINT")
      azure_version <- Sys.getenv("AZURE_OPENAI_API_VERSION")
      ellmer::chat_azure_openai(
        system_prompt = system_prompt,
        model = model,
        api_version = azure_version,
        endpoint = azure_endpoint,
        api_key = azure_key,
        type = "json_object"
      )
    },
    gemini = ellmer::chat_google_gemini(
      model = model,
      system_prompt = system_prompt,
      api_key = Sys.getenv("GEMINI_API_KEY")
    ),
    anthropic = ellmer::chat_anthropic(
      model = model,
      system_prompt = system_prompt
    ),
    ollama = ellmer::chat_ollama(model = model, system_prompt = system_prompt),
    stop("Invalid provider")
  )

  response <- tryCatch(
    {
      chat$chat(prompt)
    },
    error = function(e) {
      paste("Error invoking AI provider:", e$message)
    }
  )

  # Parse JSON
  # Clean potential markdown code blocks if the model insists on adding them
  cleaned_json <- gsub("^```json\\s*|\\s*```$", "", response)

  tryCatch(
    {
      jsonlite::fromJSON(cleaned_json)
    },
    error = function(e) {
      list(short_desc = "Error parsing JSON", long_desc = response)
    }
  )
}
