# WARNING - Generated by {fusen} from dev/flat_plots_region.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Biggest Increase in Refugee Population
#'
#'

#' @param year Numeric value of the year (for instance 2020)
#' @param lag Number of year to used as comparison base
#' @param topn how many top countries to show..
#' @param region Character value with the related UNHCR bureau - when left null,
#'              it will display the whole world
#' @param pop_type Vector of character values. Possible population type
#'                  (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#'
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  scale_color_manual scale_colour_manual
#'             geom_text
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer

#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#' @export
#' @examples
#' plot_reg_increase(
#'   year = 2021,
#'   lag = 5,
#'   topn = 5,
#'   region = "The Americas",
#'   pop_type = c("REF", "ASY", "OIP")
#' )
#'
#' plot_reg_increase(
#'   year = 2021,
#'   lag = 5,
#'   topn = 5,
#'   region = "Asia and the Pacific",
#'   pop_type = c("REF", "ASY", "OIP")
#' )
plot_reg_increase <- function(year = 2021,
                              lag = 5,
                              topn = 5,
                              region = "The Americas",
                              pop_type = c("REF", "ASY", "OIP")) {

  thisyear <- year
  baseline <- thisyear - lag

  data <- refugees::population |>
    dplyr::filter(year == baseline | year == thisyear) |>
    dplyr::mutate(unhcr_region = countrycode::countrycode(coa_iso, "iso3c", "unhcr.region")) |>
    dplyr::filter(unhcr_region == region) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::mutate(population_type_label = dplyr::case_when(
      population_type == "refugees" ~ "REF",
      population_type == "asylum_seekers" ~ "ASY",
      population_type == "idps" ~ "IDP",
      population_type == "oip" ~ "OIP",
      population_type == "stateless" ~ "STA",
      population_type == "ooc" ~ "OOC",
      population_type == "hst" ~ "HCO",
      TRUE ~ "Other"
    )) |>
    dplyr::filter(population_type_label %in% pop_type) |>
    dplyr::group_by(coa_name, year) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE), .groups = "drop") |>
    dplyr::mutate(
      coa_name = stringr::str_replace(coa_name, "Democratic Republic of the Congo", "DRC")
    ) |>
    dplyr::mutate(year = paste0("year_", year)) |>
    tidyr::spread(year, value) |>
    dplyr::mutate(gap = .data[[paste0("year_", thisyear)]] - .data[[paste0("year_", baseline)]]) |>
    dplyr::arrange(dplyr::desc(gap)) |>
    utils::head(topn)

  p <- ggplot2::ggplot(
    data,
    ggplot2::aes(
      x = .data[[paste0("year_", baseline)]],
      xend = .data[[paste0("year_", thisyear)]],
      y = stats::reorder(coa_name, gap),
      group = coa_name
    )
  ) +
    ggplot2::geom_segment(
      ggplot2::aes(
        x = .data[[paste0("year_", baseline)]],
        xend = .data[[paste0("year_", thisyear)]],
        y = stats::reorder(coa_name, gap),
        yend = stats::reorder(coa_name, gap)
      ),
      colour = "#dddddd",
      size = 3
    ) +
    ggplot2::geom_point(
      ggplot2::aes(x = .data[[paste0("year_", baseline)]], y = stats::reorder(coa_name, gap)),
      colour = "#0072bc",
      size = 3
    ) +
    ggplot2::geom_point(
      ggplot2::aes(x = .data[[paste0("year_", thisyear)]], y = stats::reorder(coa_name, gap)),
      colour = "#FAAB18",
      size = 3
    ) +
    ggplot2::labs(
      title = "Where did Refugee Population increased in the past 10 years?",
      subtitle = paste0("Biggest increase in Refugee Population, ", baseline, " - ", thisyear),
      x = "", y = "",
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    ggplot2::scale_x_continuous(labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    unhcrthemes::theme_unhcr() +
    ggplot2::theme(
      panel.grid.major.x = ggplot2::element_line(color = "#cbcbcb"),
      panel.grid.major.y = ggplot2::element_blank()
    )

  return(p)
}
  
