# WARNING - Generated by {fusen} from dev/flat_plots_country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Summary Key Figures
#'
#'  Key figures can be highlighted with humanitarian icons
#'   https://fontawesome.com/icons/categories/humanitarian
#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @return ggplot2
#'
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom ggtext geom_textbox
#' @importFrom unhcrthemes theme_unhcr
#' @importFrom countrycode countrycode
#' @importFrom tidyr pivot_longer
#' @importFrom extrafont fonttable font_import
#' @importFrom sysfonts font_add
#'
#' @export
#' @examples
#' plot_ctr_keyfig(
#'   year = 2022,
#'   country_asylum_iso3c = "COL"
#' )
plot_ctr_keyfig <- function(year = 2021,
                            country_asylum_iso3c = country_asylum_iso3c) {
  country_name_text <- refugees::population |>
    dplyr::filter(coa_iso == country_asylum_iso3c) |>
    dplyr::slice(1) |>
    dplyr::pull(coa_name)

  total_poc <- refugees::population |>
    dplyr::filter(
      year == !!year,
      coa_iso == country_asylum_iso3c
    ) |>
    dplyr::summarise(total = sum(refugees, asylum_seekers, idps, oip, stateless, ooc, hst, na.rm = TRUE)) |>
    dplyr::pull()

  # Previous year
  total_poc_prev <- refugees::population |>
    dplyr::filter(
      year == (!!year - 1),
      coa_iso == country_asylum_iso3c
    ) |>
    dplyr::summarise(total = sum(refugees, asylum_seekers, idps, oip, stateless, ooc, hst, na.rm = TRUE)) |>
    dplyr::pull()

  perc_change_poc <- (total_poc - total_poc_prev) / total_poc_prev * 100

  keyfig <- refugees::population |>
    dplyr::filter(
      year == !!year,
      coa_iso == country_asylum_iso3c
    ) |>
    tidyr::pivot_longer(
      cols = c(refugees, asylum_seekers, idps, oip, stateless, ooc, hst),
      names_to = "population_type",
      values_to = "value"
    ) |>
    dplyr::group_by(population_type) |>
    dplyr::summarise(value = sum(value, na.rm = TRUE)) |>
    dplyr::mutate(
      population_type_label = dplyr::case_when(
        population_type == "refugees" ~ "REF",
        population_type == "asylum_seekers" ~ "ASY",
        population_type == "idps" ~ "IDP",
        population_type == "oip" ~ "OIP",
        population_type == "stateless" ~ "STA",
        population_type == "ooc" ~ "OOC",
        population_type == "hst" ~ "HST",
        TRUE ~ "Other"
      )
    ) |>
    dplyr::filter(value > 0) |>
    dplyr::mutate(
      label = paste0(format(round(value, 0), big.mark = ","), " ", population_type_label),
      pal = population_type_label,
      fig = population_type_label
    )

  p <- ggplot2::ggplot(keyfig) +
    ggplot2::geom_text(
      ggplot2::aes(
        x = 0.5,
        y = 1,
        label = label,
        color = pal
      ),
      size = 6,
      hjust = 0.5,
      vjust = 0.5
    ) +
    ggplot2::scale_color_manual(values = c(
      "IDP" = "#00B398",
      "OIP" = "#EF4A60",
      "ASY" = "#18375F",
      "REF" = "#0072BC",
      "OOC" = "#8395b9",
      "STA" = "#E1CC0D"
    )) +
    ggplot2::xlim(c(0, 2)) +
    ggplot2::ylim(c(0, 3)) +
    ggplot2::facet_wrap(ggplot2::vars(fig), ncol = 2) +
    ggplot2::labs(
      title = paste0("Key Figures for ", country_name_text, " as of ", year),
      subtitle = paste0(
        "A total of ",
        format(round(total_poc, 0), scientific = FALSE, big.mark = ","),
        " people, ",
        ifelse(perc_change_poc > 0, "increasing", "decreasing"),
        " by ", round(abs(perc_change_poc), 1),
        "% compared to the previous year"
      ),
      caption = "Source: UNHCR.org/refugee-statistics"
    ) +
    ggplot2::theme_void() +
    ggplot2::theme(
      strip.text.x = ggplot2::element_text(size = 14),
      legend.position = "none"
    )
  return(p)
}
