# WARNING - Generated by {fusen} from dev/flat_plots_country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create a map with symbol proportional to population data by location within country
#'
#' @param year Numeric value of the year  (for instance 2022).
#'             If the data is not yet available for that year (aka still in the mid year reporting stage),
#'              it will automatically fall back on the previous year
#'
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param pop_type Vector of character values. Possible population type (e.g.: REF, IDP, ASY, OIP, OOC, STA)
#' @param  mapbackground can be "osm" (default), "stamen-toner" , "stamen-terrain","stamen-watercolor".
#'            Other mapbackground requires an API key and were not considered
#'
#' @importFrom ggplot2  ggplot  aes  coord_flip   element_blank element_line
#'             element_text expansion geom_bar geom_col geom_hline unit stat_summary
#'             geom_label geom_text labs  position_stack  geom_point
#'             scale_color_manual scale_colour_manual
#'             scale_size_continuous element_rect
#'             geom_text .pt theme_void
#'             scale_fill_manual scale_x_continuous scale_x_discrete  scale_y_continuous   sym theme
#' @importFrom utils  head
#' @importFrom tidyselect where
#' @importFrom stringr  str_replace str_detect  str_glue
#' @importFrom scales cut_short_scale label_percent label_number breaks_pretty
#' @importFrom stats  reorder aggregate  setNames
#' @importFrom dplyr  desc select  case_when lag mutate group_by filter summarise ungroup
#'               pull distinct n arrange across slice left_join
#' @importFrom tidyr pivot_longer pivot_wider
#' @importFrom grDevices hcl.colors
#' @importFrom unhcrthemes theme_unhcr
#'
#' @return a ggplot2 object
#'
#' @export
#'
#' @examples
#' # plot_ctr_location(year = 2022,
#' #                  country_asylum_iso3c = "COL",
#' #                  pop_type = c("ASY", "REF", "OIP"))
#' #
#' # plot_ctr_location(year = 2021,
#' #                  country_asylum_iso3c = "COL",
#' #                  pop_type = c("IDP"))
#' #
#' # plot_ctr_location(year = 2022,
#' #                  country_asylum_iso3c = "CAN",
#' #                  pop_type = c("ASY", "REF", "OIP"))
#' #
#' # plot_ctr_location(year = 2021,
#' #                  country_asylum_iso3c = "MEX",
#' #                  pop_type = c("ASY", "REF", "OIP"))
plot_ctr_location <- function(year,
                              country_asylum_iso3c,
                              pop_type,
                              mapbackground = "osm") {
  # Locate the geopackage
  gpkg_path <- system.file("extdata", "wrl_boundaries.gpkg", package = "unhcrreports")

  # Fallback for development (when package not yet installed)
  if (gpkg_path == "") {
    gpkg_path <- file.path("inst", "extdata", "wrl_boundaries.gpkg")
    if (!file.exists(gpkg_path)) {
      gpkg_path <- file.path("..", "..", "inst", "extdata", "wrl_boundaries.gpkg")
    }
  }

  if (!file.exists(gpkg_path)) {
    message("Map data not found at: ", gpkg_path)
    return(ggplot2::ggplot() +
      ggplot2::theme_void() +
      ggplot2::annotate("text", x = 0, y = 0, label = "Map data missing"))
  }

  # Read boundaries
  wrl_sf <- sf::st_read(gpkg_path, layer = "wrl_bnda_int_25m_ungis", quiet = TRUE)

  # Filter for country
  ctr_sf <- wrl_sf |> dplyr::filter(iso3cd == country_asylum_iso3c)

  if (nrow(ctr_sf) == 0) {
    message("Country ISO3 not found in map data: ", country_asylum_iso3c)
    return(ggplot2::ggplot() +
      ggplot2::theme_void())
  }

  # Plot
  p <- ggplot2::ggplot() +
    ggplot2::geom_sf(data = wrl_sf, fill = "#EAE6E4", color = "white", linewidth = 0.2) +
    ggplot2::geom_sf(data = ctr_sf, fill = "#0072BC", color = "white", linewidth = 0.5) +
    # Zoom to country with some buffer
    ggplot2::coord_sf(
      xlim = sf::st_bbox(ctr_sf)[c(1, 3)],
      ylim = sf::st_bbox(ctr_sf)[c(2, 4)],
      expand = FALSE
    ) +
    ggplot2::labs(
      title = paste0("Location of ", country_asylum_iso3c),
      caption = "Source: UNHCR"
    ) +
    unhcrthemes::theme_unhcr(void = TRUE, font_family = "sans")

  return(p)
}
