# WARNING - Generated by {fusen} from dev/flat_plots_country.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#'
#' Description

#' @param year Numeric value of the year (for instance 2020)
#' @param country_asylum_iso3c Character value with the ISO-3 character code of the Country of Asylum
#' @param lag Number of year to used as comparison base
#'

#' @importFrom unhcrthemes theme_unhcr
#' @importFrom ggtext element_markdown
#' @importFrom dplyr  desc select  filter mutate group_by filter summarise ungroup
#'               pull   full_join
#' @importFrom tidyr pivot_longer  pivot_wider
#' @importFrom lubridate ymd
#' @importFrom stringr str_wrap
#' @importFrom scales label_number cut_short_scale
#'
#' @return a ggplot2 object
#' @export
plot_ctr_solution_recognition <- function(
  year = 2021,
  lag = 10,
  country_asylum_iso3c = "UGA"
) {
  message("Solution recognition plot disabled due to missing system dependencies (ggbraid).")
  return(ggplot2::ggplot() +
    ggplot2::theme_void())
}
