# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' Render Country Report
#'
#' Renders a Quarto report for a specific country and year.
#'
#' @param country_iso3 ISO3 code of the country (e.g., "COL").
#' @param year Numeric year.
#' @param output_dir Directory to save the report.
#' @param output_file Filename for the report.
#'
#' @importFrom quarto quarto_render
#' @importFrom tools file_path_sans_ext
#' @export
#' @examples
#' \dontrun{
#' render_country_report("COL", 2022, output_dir = tempdir())
#' }
render_country_report <- function(country_iso3, year, output_dir = ".", output_file = NULL, provider = "openai", model = "gpt-4o-mini") {
    template_path <- system.file("templates", "country_report.qmd", package = "unhcrreports") # Adjust package name if needed

    # Fallback for dev mode if package not installed
    if (template_path == "") {
        template_path <- file.path("inst", "templates", "country_report.qmd")
    }

    if (!file.exists(template_path)) {
        stop("Template file not found at: ", template_path)
    }

    if (is.null(output_file)) {
        output_file <- paste0("report_", country_iso3, "_", year, ".html")
    }

    # Ensure output directory exists
    if (!dir.exists(output_dir)) {
        dir.create(output_dir, recursive = TRUE)
    }

    # Copy template to output directory to avoid writing to package dir
    temp_template <- file.path(output_dir, "country_report.qmd")
    file.copy(template_path, temp_template, overwrite = TRUE)

    # Render the copy
    quarto::quarto_render(
        input = temp_template,
        output_file = output_file,
        execute_params = list(
            country_iso3 = country_iso3,
            year = year,
            gp_provider = provider,
            gp_model = model,
            package_path = getwd() # Pass current working directory as package root
        )
    )

    # Clean up template copy
    file.remove(temp_template)

    return(file.path(output_dir, output_file))
}
