# WARNING - Generated by {fusen} from dev/flat_ai_reporting.Rmd: do not edit by hand # nolint: line_length_linter.

#' slugify
#'
#' Convert string to slug
#'
#' @param x the string
#'
#' @return slugified string
#' @importFrom stringr str_to_lower str_replace_all str_remove_all str_squish
#' @importFrom stringi stri_enc_toutf8
#' @export
#' @examples
#' strings <- c(
#'   "Café au Lait",
#'   "Niño Español",
#'   "Data_Science_Project",
#'   "--test--string--"
#' )
#' slugify(strings)
slugify <- function(x) {
  x |>
    stringi::stri_enc_toutf8() |>
    # Remove extra whitespace first
    stringr::str_squish() |>
    # Convert to lowercase
    stringr::str_to_lower() |>
    # Replace accented characters with their ASCII equivalents
    stringr::str_replace_all("[àáâãäå]", "a") |>
    stringr::str_replace_all("[èéêë]", "e") |>
    stringr::str_replace_all("[ìíîï]", "i") |>
    stringr::str_replace_all("[òóôõöø]", "o") |>
    stringr::str_replace_all("[ùúûü]", "u") |>
    stringr::str_replace_all("[ñ]", "n") |>
    stringr::str_replace_all("[ç]", "c") |>
    stringr::str_replace_all("[ýÿ]", "y") |>
    stringr::str_replace_all("[ž]", "z") |>
    # Remove all non-alphanumeric characters except spaces, underscores, hyphens
    stringr::str_replace_all("[^a-z0-9\\s_-]", "") |>
    # Replace spaces and underscores with hyphens
    stringr::str_replace_all("[\\s_]+", "-") |>
    # Remove consecutive hyphens
    stringr::str_replace_all("-+", "-") |>
    # Remove leading/trailing hyphens
    stringr::str_remove_all("^-|-$")
}
